export const TRAVEL_HOROSCOPES = {
  positive: [
    "The stars align perfectly for your journey today. Smooth skies and tailwinds await you.",
    "Mercury is in your favor - expect punctual departures and swift arrivals.",
    "Your travel guardian angel is working overtime today. Safe travels are assured.",
    "The cosmic winds blow in your direction. Your flight will be a breeze.",
    "Jupiter's blessing shines upon your travels. Comfort and timeliness are yours.",
    "The universe conspires to make your journey pleasant and on-time.",
    "Your travel karma is exceptionally positive today. Expect delightful surprises.",
    "The celestial bodies dance in harmony for your safe passage.",
    "Today's planetary alignment favors swift and comfortable travel.",
    "Your journey is blessed by favorable cosmic currents.",
    "The travel gods smile upon you - expect smooth sailing through the skies.",
    "Your flight path is illuminated by lucky stars.",
    "The winds of fortune carry you swiftly to your destination.",
    "Today brings perfect travel conditions written in the stars.",
    "Your departure time is cosmically blessed for success.",
    "The universe opens clear pathways for your journey.",
    "Stellar energy surrounds your travel plans with protection.",
    "Your flight is guided by benevolent cosmic forces.",
    "The stars whisper of comfortable seats and friendly service.",
    "Today's astral climate is ideal for air travel.",
    "Your journey unfolds under a canopy of fortunate stars.",
    "The cosmic compass points toward smooth travels.",
    "Your flight is blessed with celestial tailwinds.",
    "The universe aligns to make your travel dreams come true.",
    "Today's stellar forecast promises delightful travel experiences."
  ],
  negative: [
    "The stars suggest patience will be your greatest virtue today. Delays may test your resolve.",
    "Mercury retrograde casts shadows on your travel plans. Expect the unexpected.",
    "The cosmic currents are turbulent today. Your journey may face headwinds.",
    "The travel spirits are restless - prepare for a bumpy ride through the skies.",
    "Saturn's influence brings lessons in patience during your travels today.",
    "The universe tests your adaptability with travel challenges ahead.",
    "Your journey is written in the stars, but the ink is still wet and smudging.",
    "The celestial forecast shows stormy skies for your travel plans.",
    "Today's planetary alignment suggests bringing extra snacks and entertainment.",
    "The cosmic winds blow against you - patience will be your companion.",
    "Your travel guardian angel is taking a coffee break today.",
    "The stars align to teach you the art of waiting gracefully.",
    "Mercury's mischief may scramble your departure times today.",
    "The universe has enrolled you in advanced patience training.",
    "Your flight path is decorated with cosmic speed bumps.",
    "The travel gods are playing practical jokes today - stay flexible.",
    "Today's astral weather includes heavy doses of delay energy.",
    "The stars suggest downloading extra movies for your extended journey.",
    "Your departure gate may become your temporary home today.",
    "The cosmic schedule runs on a different timezone than yours.",
    "The universe is stress-testing your zen travel attitude.",
    "Today's stellar forecast includes scattered delays with a chance of frustration.",
    "The celestial air traffic control is experiencing technical difficulties.",
    "Your journey is blessed with character-building travel experiences.",
    "The stars align to make you appreciate punctual flights in the future."
  ]
};
